apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-db
  labels:
    {{- include "helm-chart.labelsDb" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.db }}
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "helm-chart.selectorLabelsDb" . | nindent 4 }}
