apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-frontend
  labels:
    {{- include "helm-chart.labelsFrontend" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.frontend }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabelsFrontend" . | nindent 4 }}
