apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: cr.yandex/crpqphpbdbm50fs7ovm6/frontend:latest
        ports:
        - containerPort: 80
      - name: backend
        image: cr.yandex/crpqphpbdbm50fs7ovm6/backend:latest
        ports:
          - containerPort: 9000
