apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    stdin: true
    tty: true
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
    env:
      - name: TLS_CERT
        valueFrom:
          secretKeyRef:
            name: domain-cert
            key: tls.crt
      - name: TLS_KEY
        valueFrom:
          secretKeyRef:
            name: domain-cert
            key: tls.key
    volumeMounts:
      - mountPath: /secret
        name: secret
        readOnly: true

  volumes:
    - name: secret
      secret:
        secretName: domain-cert
